mysql:
  user: username
  port: 3306
  password: password
  host: localhost
  database: database
  tablePrefix: uc_
disabledWorlds: [world1, world2, world3]
visualizationMaterialOne: GLASS
visualizationMaterialTwo: GLOWSTONE
visualizeOnNonAirBlocks: true
width: 30
length: 30
height: 30
maxPlayers: 10
minPlayers: 4
banksEnabled: false
startingBalance: 0
costCreate: 2500
costExtend: 1500
extensionTime: 7